spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    #    For local usage
    url: jdbc:postgresql://localhost:5432/weather-analyzer
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port

#API
weather.api:
  token: 3e3f38adc7cd3182c5cca0a70a33bc2e
  urls:
    current: http://api.weatherstack.com/current?query={query}&units={units}

openapi:
  title: Admin Panel
  version: 1.0.0
  description: This is  pre from end UI